# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodle',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False, unique=True, verbose_name='url')),
                ('ind', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('subtitle', models.CharField(max_length=2048)),
                ('date', models.CharField(max_length=1024)),
                ('photo', models.CharField(max_length=1024)),
            ],
        ),
    ]
