# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodle',
        ),
    ]
